version: '3.8'

services:
  mysql-db:
    image: mysql:8.0
    container_name: mysql-competence
    environment:
      MYSQL_DATABASE: competence_db
      MYSQL_ROOT_PASSWORD: youssef
      MYSQL_USER: user
      MYSQL_PASSWORD: userpass
    ports:
      - "3306:3306"
    volumes:
      - mysql-data:/var/lib/mysql
    networks:
      - springboot-network

  app:
    build: .
    container_name: spring-competence-app
    ports:
      - "8080:8080"
    depends_on:
      - mysql-db
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://mysql-db:3306/competence_db?useSSL=false&allowPublicKeyRetrieval=true&serverTimezone=UTC
      SPRING_DATASOURCE_USERNAME: root
      SPRING_DATASOURCE_PASSWORD: youssef
    networks:
      - springboot-network

volumes:
  mysql-data:

networks:
  springboot-network:
